# appveyor.yml
---
image: Ubuntu
environment:
  matrix:
  - TOXENV: py27
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37

build: off

install:
- sudo apt-get install -y python3
- sudo apt-get install -y python3-bs4
- pip install -r requirements.txt

test_script:
- cd src
- python3 bsfconsole.py -v
